// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexModuleLessNamespace {
  export interface IIndexModuleLess {
    featList: string
    homePartner: string
    indexPage: string
    narrowerFeatWrap: string
    partner: string
    slogan: string
  }
}

declare const IndexModuleLessModule: IndexModuleLessNamespace.IIndexModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexModuleLessNamespace.IIndexModuleLess
}

export = IndexModuleLessModule
