// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ActionPopoverModuleLessNamespace {
  export interface IActionPopoverModuleLess {
    popoverBtn: string
  }
}

declare const ActionPopoverModuleLessModule: ActionPopoverModuleLessNamespace.IActionPopoverModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ActionPopoverModuleLessNamespace.IActionPopoverModuleLess
}

export = ActionPopoverModuleLessModule
