// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ButtonContainerModuleLessNamespace {
  export interface IButtonContainerModuleLess {
    buttonContainer: string
    buttons: string
  }
}

declare const ButtonContainerModuleLessModule: ButtonContainerModuleLessNamespace.IButtonContainerModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ButtonContainerModuleLessNamespace.IButtonContainerModuleLess
}

export = ButtonContainerModuleLessModule
