// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace InstallReminderModuleLessNamespace {
  export interface IInstallReminderModuleLess {
    btns: string
    link: string
    reminder: string
  }
}

declare const InstallReminderModuleLessModule: InstallReminderModuleLessNamespace.IInstallReminderModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: InstallReminderModuleLessNamespace.IInstallReminderModuleLess
}

export = InstallReminderModuleLessModule
