// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace LottieModuleLessNamespace {
  export interface ILottieModuleLess {
    lottie: string
  }
}

declare const LottieModuleLessModule: LottieModuleLessNamespace.ILottieModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LottieModuleLessNamespace.ILottieModuleLess
}

export = LottieModuleLessModule
