// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MnemonicListModuleLessNamespace {
  export interface IMnemonicListModuleLess {
    copy: string
    error: string
    isInput: string
    mnemonicList: string
  }
}

declare const MnemonicListModuleLessModule: MnemonicListModuleLessNamespace.IMnemonicListModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MnemonicListModuleLessNamespace.IMnemonicListModuleLess
}

export = MnemonicListModuleLessModule
