// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MpcStateModuleLessNamespace {
  export interface IMpcStateModuleLess {
    loading: string
    mpcState: string
    percent: string
    success: string
  }
}

declare const MpcStateModuleLessModule: MpcStateModuleLessNamespace.IMpcStateModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MpcStateModuleLessNamespace.IMpcStateModuleLess
}

export = MpcStateModuleLessModule
