// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ScanQrcodeModuleLessNamespace {
  export interface IScanQrcodeModuleLess {
    scanQrcode: string
  }
}

declare const ScanQrcodeModuleLessModule: ScanQrcodeModuleLessNamespace.IScanQrcodeModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ScanQrcodeModuleLessNamespace.IScanQrcodeModuleLess
}

export = ScanQrcodeModuleLessModule
