// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StepTextModuleLessNamespace {
  export interface IStepTextModuleLess {
    active: string
    icon: string
    line: string
    loading: string
    loadingImg: string
    rotate: string
    stepContent: string
    success: string
  }
}

declare const StepTextModuleLessModule: StepTextModuleLessNamespace.IStepTextModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StepTextModuleLessNamespace.IStepTextModuleLess
}

export = StepTextModuleLessModule
