// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StepContainerModuleLessNamespace {
  export interface IStepContainerModuleLess {
    buttonContent: string
    left: string
    right: string
    stepContainer: string
  }
}

declare const StepContainerModuleLessModule: StepContainerModuleLessNamespace.IStepContainerModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StepContainerModuleLessNamespace.IStepContainerModuleLess
}

export = StepContainerModuleLessModule
