// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StepProgressModuleLessNamespace {
  export interface IStepProgressModuleLess {
    active: string
    stepProgress: string
  }
}

declare const StepProgressModuleLessModule: StepProgressModuleLessNamespace.IStepProgressModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StepProgressModuleLessNamespace.IStepProgressModuleLess
}

export = StepProgressModuleLessModule
