// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace WebRtcConnectionModuleLessNamespace {
  export interface IWebRtcConnectionModuleLess {
    mainTitle: string
    subTitle: string
    tipTitle: string
    webrtcConnection: string
  }
}

declare const WebRtcConnectionModuleLessModule: WebRtcConnectionModuleLessNamespace.IWebRtcConnectionModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: WebRtcConnectionModuleLessNamespace.IWebRtcConnectionModuleLess
}

export = WebRtcConnectionModuleLessModule
