// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace AddressCardModuleLessNamespace {
  export interface IAddressCardModuleLess {
    account: string
    action: string
    address: string
    addressCard: string
    addressDialog: string
    backup: string
    dashboardContent: string
    dashboardLogo: string
    dashboardWrapper: string
    more: string
    network: string
    qrcode: string
  }
}

declare const AddressCardModuleLessModule: AddressCardModuleLessNamespace.IAddressCardModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AddressCardModuleLessNamespace.IAddressCardModuleLess
}

export = AddressCardModuleLessModule
