// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace BackupDialogModuleLessNamespace {
  export interface IBackupDialogModuleLess {
    about: string
    action: string
    backupDialog: string
    info: string
    infoList: string
    success: string
    warnList: string
  }
}

declare const BackupDialogModuleLessModule: BackupDialogModuleLessNamespace.IBackupDialogModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: BackupDialogModuleLessNamespace.IBackupDialogModuleLess
}

export = BackupDialogModuleLessModule
