// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CreateOrImportGuideModuleLessNamespace {
  export interface ICreateOrImportGuideModuleLess {
    box: string
    disabled: string
    guide: string
    line: string
    tip: string
  }
}

declare const CreateOrImportGuideModuleLessModule: CreateOrImportGuideModuleLessNamespace.ICreateOrImportGuideModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CreateOrImportGuideModuleLessNamespace.ICreateOrImportGuideModuleLess
}

export = CreateOrImportGuideModuleLessModule
