// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CreateDialogModuleLessNamespace {
  export interface ICreateDialogModuleLess {
    createDialog: string
  }
}

declare const CreateDialogModuleLessModule: CreateDialogModuleLessNamespace.ICreateDialogModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: CreateDialogModuleLessNamespace.ICreateDialogModuleLess
}

export = CreateDialogModuleLessModule
