// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace MnemonicFormModuleLessNamespace {
  export interface IMnemonicFormModuleLess {
    done: string
    mnemonicForm: string
    noNeed: string
    skip: string
  }
}

declare const MnemonicFormModuleLessModule: MnemonicFormModuleLessNamespace.IMnemonicFormModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: MnemonicFormModuleLessNamespace.IMnemonicFormModuleLess
}

export = MnemonicFormModuleLessModule
