// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace NotBackupDialogModuleLessNamespace {
  export interface INotBackupDialogModuleLess {
    notBackupDialog: string
  }
}

declare const NotBackupDialogModuleLessModule: NotBackupDialogModuleLessNamespace.INotBackupDialogModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: NotBackupDialogModuleLessNamespace.INotBackupDialogModuleLess
}

export = NotBackupDialogModuleLessModule
