// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RecoverDialogModuleLessNamespace {
  export interface IRecoverDialogModuleLess {
    recoverDialog: string
  }
}

declare const RecoverDialogModuleLessModule: RecoverDialogModuleLessNamespace.IRecoverDialogModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: RecoverDialogModuleLessNamespace.IRecoverDialogModuleLess
}

export = RecoverDialogModuleLessModule
