// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace RecoverPrepareDialogModuleLessNamespace {
  export interface IRecoverPrepareDialogModuleLess {
    recoverPrepareDialog: string
  }
}

declare const RecoverPrepareDialogModuleLessModule: RecoverPrepareDialogModuleLessNamespace.IRecoverPrepareDialogModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: RecoverPrepareDialogModuleLessNamespace.IRecoverPrepareDialogModuleLess
}

export = RecoverPrepareDialogModuleLessModule
