// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SendDialogModuleLessNamespace {
  export interface ISendDialogModuleLess {
    amount: string
    confirmDialog: string
    confirmForm: string
    fee: string
    formAmount: string
    info: string
    infoItem: string
    sendDialog: string
    sendForm: string
  }
}

declare const SendDialogModuleLessModule: SendDialogModuleLessNamespace.ISendDialogModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SendDialogModuleLessNamespace.ISendDialogModuleLess
}

export = SendDialogModuleLessModule
