// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace TransactionListModuleLessNamespace {
  export interface ITransactionListModuleLess {
    container: string
    emptyContainer: string
    emptyTipList: string
    record: string
    riskText: string
    subTitle: string
    title: string
  }
}

declare const TransactionListModuleLessModule: TransactionListModuleLessNamespace.ITransactionListModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: TransactionListModuleLessNamespace.ITransactionListModuleLess
}

export = TransactionListModuleLessModule
