// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace WalletNameDialogModuleLessNamespace {
  export interface IWalletNameDialogModuleLess {
    nameForm: string
    walletName: string
  }
}

declare const WalletNameDialogModuleLessModule: WalletNameDialogModuleLessNamespace.IWalletNameDialogModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: WalletNameDialogModuleLessNamespace.IWalletNameDialogModuleLess
}

export = WalletNameDialogModuleLessModule
