// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace WelcomeModuleLessNamespace {
  export interface IWelcomeModuleLess {
    imgBox: string
    welcome: string
  }
}

declare const WelcomeModuleLessModule: WelcomeModuleLessNamespace.IWelcomeModuleLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: WelcomeModuleLessNamespace.IWelcomeModuleLess
}

export = WelcomeModuleLessModule
